# Generated by Django 3.0.8 on 2020-11-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('Auth_Id', models.TextField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('House', models.CharField(max_length=100)),
                ('Parish', models.CharField(max_length=50)),
                ('Village', models.CharField(max_length=50)),
                ('Panch_Muns', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=30)),
                ('Farming', models.CharField(max_length=5)),
                ('Rubber', models.CharField(max_length=5)),
                ('Animal', models.CharField(max_length=5)),
                ('Vegitables_Fruits', models.CharField(max_length=5)),
                ('Fish', models.CharField(max_length=5)),
                ('Created_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth_Name', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=15)),
                ('Message', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VegFru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
                ('Land_Area', models.CharField(max_length=10)),
                ('Income', models.CharField(max_length=10)),
                ('Marketing', models.CharField(max_length=20)),
                ('Breed', models.CharField(max_length=5)),
                ('More_Space', models.CharField(max_length=5)),
                ('More_Intrest', models.CharField(max_length=5)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.BasicDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intrest', models.CharField(max_length=5)),
                ('Jobs', models.CharField(max_length=110)),
                ('Business', models.CharField(max_length=110)),
                ('News_Paper', models.CharField(max_length=50)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.BasicDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
                ('Land_Area', models.CharField(max_length=10)),
                ('Method', models.CharField(max_length=15)),
                ('Income', models.CharField(max_length=10)),
                ('Marketing', models.CharField(max_length=20)),
                ('More_Space', models.CharField(max_length=5)),
                ('More_Intrest', models.CharField(max_length=5)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.BasicDetails')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Relationship', models.CharField(max_length=15)),
                ('Blood', models.CharField(max_length=5)),
                ('Job', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.BasicDetails')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticAnimals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
                ('Count', models.CharField(max_length=10)),
                ('Income', models.CharField(max_length=10)),
                ('Marketing', models.CharField(max_length=20)),
                ('Breed', models.CharField(max_length=5)),
                ('More_Space', models.CharField(max_length=5)),
                ('More_Intrest', models.CharField(max_length=5)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.BasicDetails')),
            ],
        ),
    ]
