# Generated by Django 3.0.8 on 2020-12-04 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='Auth_Id',
            field=models.TextField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Rubber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Land_Area', models.CharField(max_length=10)),
                ('Count', models.CharField(max_length=10)),
                ('Income', models.CharField(max_length=10)),
                ('Rubber_Sheet', models.CharField(max_length=20)),
                ('Rubber_Board', models.CharField(max_length=5)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.BasicDetails')),
            ],
        ),
    ]
