# Generated by Django 3.0.8 on 2020-12-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201204_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domesticanimals',
            old_name='Breed',
            new_name='Weed',
        ),
        migrations.RenameField(
            model_name='vegfru',
            old_name='Breed',
            new_name='Weed',
        ),
    ]
