# Generated by Django 3.1.4 on 2020-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201209_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Business',
            field=models.CharField(default=None, max_length=110),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='Intrest',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='Jobs',
            field=models.CharField(default=None, max_length=110),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='News_Paper',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
