# Generated by Django 3.1.4 on 2020-12-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20201209_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdetails',
            old_name='Animal',
            new_name='DomesticAnimals',
        ),
        migrations.RenameField(
            model_name='basicdetails',
            old_name='Vegitables_Fruits',
            new_name='VegFru',
        ),
    ]
