# Generated by Django 3.0.8 on 2020-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20201212_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubber',
            name='Land_Area',
            field=models.CharField(max_length=30),
        ),
    ]
