# Generated by Django 3.0.8 on 2020-12-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20201229_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='Method',
            field=models.CharField(max_length=25),
        ),
    ]
