# Generated by Django 3.0.8 on 2020-12-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20201229_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='District',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='Job',
            field=models.CharField(max_length=30),
        ),
    ]
