# Generated by Django 3.0.8 on 2020-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20201231_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Business',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Jobs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='News_Paper',
            field=models.TextField(),
        ),
    ]
